server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true

quickfixj:
  server:
    enabled: true
  client:
    enabled: true

management:
  endpoint:
    quickfixjclient:
      enabled: true
    quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjclient,quickfixjserver

logging:
  level:
    root: info
